#!/bin/bash

# CloudCompass Deployment Status Check Script

echo "🧭 CloudCompass Deployment Status Check"
echo "======================================="

echo ""
echo "📋 Current Status:"
echo "GitHub Actions build is failing. Let's diagnose the issue."
echo ""

echo "🔧 Manual Steps Required:"
echo "========================"
echo ""
echo "1. Check GitHub Pages Settings:"
echo "   Go to: https://github.com/AAkinDev/CloudCompass/settings/pages"
echo "   Ensure Source is set to: 'GitHub Actions'"
echo ""
echo "2. Check GitHub Actions:"
echo "   Go to: https://github.com/AAkinDev/CloudCompass/actions"
echo "   Look for the latest workflow run and check the logs"
echo ""
echo "3. Expected Debug Output:"
echo "   The enhanced workflow will show:"
echo "   - Repository contents"
echo "   - Public directory contents"
echo "   - Node.js and npm versions"
echo "   - Whether index.html exists"
echo "   - Build directory contents"
echo ""

echo "🎯 Common Issues and Solutions:"
echo "=============================="
echo ""
echo "❌ Issue: 'Could not find a required file. Name: index.html'"
echo "✅ Solution: This usually means the build process is failing before creating the build directory"
echo ""
echo "❌ Issue: GitHub Pages showing README instead of React app"
echo "✅ Solution: Change Pages source from 'Deploy from a branch' to 'GitHub Actions'"
echo ""
echo "❌ Issue: Build fails in CI but works locally"
echo "✅ Solution: Check Node.js version compatibility or missing dependencies"
echo ""

echo "📊 Local Build Status:"
echo "====================="
if npm run build > /dev/null 2>&1; then
    echo "✅ Local build successful"
    echo "✅ Build directory exists"
    echo "✅ index.html found in build/"
else
    echo "❌ Local build failed"
    echo "Please check the build errors above"
fi

echo ""
echo "🔍 Next Steps:"
echo "=============="
echo "1. Wait for the enhanced workflow to complete"
echo "2. Check the detailed logs in GitHub Actions"
echo "3. Verify GitHub Pages settings"
echo "4. Once deployed, visit: https://AAkinDev.github.io/CloudCompass"
echo ""
echo "📞 If issues persist:"
echo "- Check the GitHub Actions logs for specific error messages"
echo "- Verify all files are committed and pushed"
echo "- Ensure the repository is public or you have GitHub Pro"
echo ""
echo "Happy debugging! 🚀" 