name: Deploy CloudCompass to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Debug repository contents
      run: |
        echo "Repository contents:"
        ls -la
        echo "Current working directory:"
        pwd
        echo "Public directory contents (if exists):"
        ls -la public/ || echo "Public directory not found"
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Debug Node.js and npm
      run: |
        echo "Node.js version:"
        node --version
        echo "npm version:"
        npm --version
        echo "Current directory:"
        pwd
        
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
      
    - name: Verify public files exist
      run: |
        echo "Checking if we're in the right directory:"
        pwd
        echo "Repository contents:"
        ls -la
        echo "Checking public directory contents:"
        if [ -d "public" ]; then
          ls -la public/
          echo "✅ Public directory found"
        else
          echo "❌ Public directory not found"
          echo "Creating public directory with required files..."
          mkdir -p public
          echo '<!DOCTYPE html><html><head><title>CloudCompass</title></head><body><div id="root"></div></body></html>' > public/index.html
        fi
        echo "Checking if index.html exists:"
        if [ -f "public/index.html" ]; then
          echo "✅ index.html found"
          echo "index.html content (first 5 lines):"
          head -5 public/index.html
        else
          echo "❌ index.html missing"
        fi
        
    - name: Run tests
      run: npm test -- --watchAll=false --passWithNoTests
      
    - name: Build application
      run: npm run build
      
    - name: Verify build output
      run: |
        echo "Checking build directory contents:"
        ls -la build/ || echo "Build directory not found"
        echo "Checking if build/index.html exists:"
        if [ -f "build/index.html" ]; then
          echo "✅ build/index.html found"
          echo "build/index.html content (first 5 lines):"
          head -5 build/index.html
        else
          echo "❌ build/index.html missing"
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 